# This gitlab-ci file is used for creating building pages directories for nofusscomputing.com.
# by including this file, the jobs will be autocreated and only for pages jobs.

include:
  - local: $JOB_ROOT_DIR/.gitlab-ci_common.yaml
  - local: $JOB_ROOT_DIR/mkdocs/.gitlab-ci.yml
  - local: $JOB_ROOT_DIR/lint/markdown.gitlab-ci.yaml


Documentation.Lint:
  extends: .Lint_Markdown_Docs


Documentation.Build:
  extends: .MKDocs_Build_Docs
  needs: [ 'Documentation.Lint' ]


Documentation.Deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - mv "$CI_PROJECT_DIR/artifacts/build/Documentation.Build/build" public
  needs: [ 'Documentation.Build' ]
  environment: 
    name: staging
    url: $CI_PAGES_URL/$PAGES_ENVIRONMENT_PATH
  artifacts:
    paths:
      - public
  rules:
    - if: '$JOB_STOP_GITLAB_PAGES'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_BRANCH == "development" && 
          ( $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "pipeline")'
      exists:
        - "mkdocs.yaml"
        - "mkdocs.yml"
      when: always
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master" && 
          ( $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "pipeline")'
      exists:
        - "mkdocs.yaml"
        - "mkdocs.yml"
      when: manual
      allow_failure: true
    - when: never