# This gitlab-ci file is used for creating building pages directories for nofusscomputing.com.
# by including this file, the jobs will be autocreated and only for pages jobs.

include:
  - local: $JOB_ROOT_DIR/.gitlab-ci_common.yaml
  - local: $JOB_ROOT_DIR/mkdocs/.gitlab-ci.yml
  - local: $JOB_ROOT_DIR/lint/markdown.gitlab-ci.yaml


Website.Lint:
  extends: .Lint_Markdown_Docs


Website.Build:
  variables:
    MKDOCS_SOURCE_PATH: docs
  extends: .MKDocs_Build
  needs: [ 'Website.Lint' ]


pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
    PAGES_ENVIRONMENT_PATH: ''
  script:
    - mv "$CI_PROJECT_DIR/artifacts/build/Website.Build/build" public
  needs: [ 'Website.Build' ]
  environment: 
    name: staging
    url: $CI_PAGES_URL/$PAGES_ENVIRONMENT_PATH
  artifacts:
    paths:
      - public
  rules:
    - if: '$JOB_STOP_GITLAB_PAGES'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_BRANCH == "development" && $CI_PIPELINE_SOURCE == "push"'
      exists:
        - "mkdocs.yaml"
        - "mkdocs.yml"
      when: always
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "push"'
      exists:
        - "mkdocs.yaml"
        - "mkdocs.yml"
      when: manual
      allow_failure: true
    - when: never