# This gitlab-ci file is used for creating building pages directories for nofusscomputing.com.
# by including this file, the jobs will be autocreated and only for pages jobs.

include:
  - local: $JOB_ROOT_DIR/.gitlab-ci_common.yaml
  - local: $JOB_ROOT_DIR/mkdocs/.gitlab-ci.yml
  - local: $JOB_ROOT_DIR/lint/markdown.gitlab-ci.yml


Website Page Linting:
  extends: .Lint_Markdown_Pages


Website:
  extends: .MKDocs_Build
  needs: [ 'Website Page Linting' ]


pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - mv "$CI_PROJECT_DIR/artifacts/build/Website/build" public
  needs: [ 'Website' ]
  environment: 
    name: staging
    url: $CI_PAGES_URL/projects/gitlab-ci/
  artifacts:
    paths:
    - public
  rules:
    - if: '$JOB_STOP_GITLAB_PAGES'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master"'
      exists:
        - "mkdocs.yaml"
        - "mkdocs.yml"
      when: on_success
    - when: never