commitizen:
  bump_message: "build(version): bump version $current_version \u2192 $new_version"
  changelog_incremental: false
  name: cz_conventional_commits
  tag_format: $major.$minor.$patch$prerelease
  update_changelog_on_bump: true
  version: 0.7.0rc0
