variables:
    JOB_ROOT_DIR: 'gitlab-ci'
    GIT_SUBMODULE_STRATEGY: recursive


stages:
    - chores
    - validation
    - build
    - prepare
    - test
    - release
    - sync
    - deploy
    - publish
