variables:
    JOB_ROOT_DIR: '.'
    GIT_SUBMODULE_STRATEGY: recursive
    MY_PROJECT_ID: "28543717"

stages:
    - validation
    - release
    - sync

include:
  - local: $JOB_ROOT_DIR/yaml_lint/.gitlab-ci.yml
  - local: $JOB_ROOT_DIR/conventional_commits/.gitlab-ci.yml
  - local: $JOB_ROOT_DIR/git_push_mirror/.gitlab-ci.yml
  - local: $JOB_ROOT_DIR/gitlab_release/.gitlab-ci.yml
  - local: $JOB_ROOT_DIR/python/.gitlab-ci.yml

PyLint:
    extends:
        - .PyLint
    image: python:3.6-slim


gilab-ci.yml Lint (python 3.6):
    variables:
        YAML_LINT_PATH: "/*/.gitlab-ci.yml"
    extends:
        - .yaml_lint_defaults
    image: python:3.6-slim


Gitlab Release:
    variables:
        MY_COMMAND: ./sub-folder_changlog.sh
    extends:
        - .gitlab_release


Github (Push --mirror):
    variables:
        GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/gitlab-ci.git"
    extends:
        - .git_push_mirror
