INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Gitlab-CI
repo_url: https://gitlab.com/nofusscomputing/projects/gitlab-ci
edit_uri: '/-/ide/project/nofusscomputing/projects/gitlab-ci/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Gitlab CI:

    - Ansible:

      - projects/gitlab-ci/ansible/collection.md

    - Build:
      
      - projects/gitlab-ci/docker_build.md

      - projects/gitlab-ci/mkdocs-build.md

    - Chores:

      - projects/gitlab-ci/ansible_playbook.md

    - Linting:

      - projects/gitlab-ci/markdown_lint.md

      - projects/gitlab-ci/yaml_lint.md

    - Publish:
      
      - projects/gitlab-ci/docker_publish.md

    - Templates:
      
      - projects/gitlab-ci/templates/index.md
    
      - projects/gitlab-ci/templates/ansible_roles.md

      - projects/gitlab-ci/templates/automagic.md

      - projects/gitlab-ci/templates/docker_container.md

      - projects/gitlab-ci/templates/documentation_mkdocs.md

    - Validation:

      - projects/gitlab-ci/conventional_commits.md

    - projects/gitlab-ci/index.md

    - projects/gitlab-ci/git_mirror.md

    - projects/gitlab-ci/gitlab_release.md

    - projects/gitlab-ci/python.md

- Operations: 

  - operations/index.md

- Contact Us: contact.md

